### ISSUE TITLE
New KV API Observe all keys

### ISSUE THREAD

**Issue by Toshbrown** [jptmoore/zest#18]
Currently, the observe endpoint will allow you to watch for changes on a single key `/observe/<DsId>/<keyName>`.

It would be useful to be able to watch for changes on any key, using something like this:

`/observe/<DsId>`

It should send 
```
{"key":"<name of key>","value":"<data stored at key>"}
```

**Comment by jptmoore** [comment]
Can observe path using wildcard e.g. '/kv/sensor/*' and data now comes in a format like:

1521490024 /kv/sensor/foo json {"room": "lounge", "value": 1}
